### PR TITLE
Add a new feature: Qos Limter

### PR DESCRIPTION
**Pull request by hang666**
---
name: Pull request
about: Add a new feature
title: ''
labels: ''
assignees: ''
---

## 1. Are you opening this pull request for bug-fixs, optimizations or new feature?
new feature

## 2. Please describe how these code changes achieve your intention.

I will add a QoS (Quality of Service) limiting feature, which allows restricting the number of executing threads within a specified time window.
This will help control the concurrency of thread execution, enhancing application stability and performance.
It increases the flexibility of the ants Goroutine Pool library to accommodate specific application requirements.
It provides fine-grained control over the number of executing threads within a specified time window.

## 4. Which documentation changes (if any) need to be made/updated because of this PR?

README document needs to be updated to add a description of the QoS restriction feature.

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [x] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] (optional) I am willing to help maintain this change if there are issues with it later.

### CODE REVIEW

**Comment by panjf2000** [comment]
I couldn't think of any scenarios for a goroutine pool to do rate limiting, could you back your PR up with some real-world use cases?

**Comment by hang666** [comment]
> I couldn't think of any scenarios for a goroutine pool to do rate limiting, could you back your PR up with some real-world use cases?

我当前的应用场景是需要访问一个api来进行批量数据更新，但是服务商有速率限制，为了避免超出qos限制而出现大量垃圾请求才做的这个。
另外我看了github中的Dependency graph，发现有很多使用ants的项目都是进行采集抓取等网络操作，如果考虑到请求太频繁被ban，基本会都有这种需求。

**Comment by panjf2000** [comment]
pool 本身做限流并不合理，因为 pool 的目的仅仅是为了复用资源，限流这种需求应该要有一个单独的 rate limiter 和 pool 包装在一起使用或者直接在用户的 func 里实现。

**Comment by hang666** [comment]
> pool 本身做限流并不合理，因为 pool 的目的仅仅是为了复用资源，限流这种需求应该要有一个单独的 rate limiter 和 pool 包装在一起使用或者直接在用户的 func 里实现。

好的谢谢，我一开始其实也想着单独实现，不过看了一下很多使用ants的项目都是类似的这种业务，加上不会有什么额外开销，才想着搞

**Comment by panjf2000** [comment]
library 还是要保持职责单一，`ants` 是一个 goroutine pool，所以只需要做好这方面的事即可，我不希望引入一些不必要的功能和代码导致 `ants` 这个 library 变得臃肿，不过还是谢谢你在这上面付出的时间，期待以后你能有新的想法。

**Pull request closed without merging**
