### PR TITLE
add more  test about spinlock

### LINKED ISSUE #191: 自旋锁的性能对比测试
测试案例代码 
https://github.com/liu-song/ants/blob/master/internal/spinlock_test.go

### PR DESCRIPTION
**Pull request by liu-song**
---
name: Pull request
about:  add more test about spinlock
title: ''
labels: ''
assignees: ''
---

## 1. Are you opening this pull request for bug-fixs, optimizations or new feature?
     just add more test about spinlock

## 2. Please describe how these code changes achieve your intention.

 
Simulate the performance comparison of spinlock with and without backoff and mutex in different scenarios

## 3. Please link to the relevant issues (if any).

Fixes #191 

## 4. Checklist

- [x] I have squashed all insignificant commits.
- [x] I have commented my code for explaining package types, values, functions, and non-obvious lines.
- [x] I have written unit tests and verified that all tests passes (if needed).
- [ ] I have documented feature info on the README (only when this PR is adding a new feature).
- [x] I (optional) I am willing to help maintain this change if there are issues with it later.

### CODE REVIEW

**Comment by liu-song** [comment]
also ping @panjf2000

**Comment by panjf2000** [comment]
这个不太好掌控，启动之时用什么类型的锁已经定死了，真正运行过程中是什么情况也无法知晓。

**Review by panjf2000 — CHANGES_REQUESTED** [review]
格式化一下代码文件。

**Comment by liu-song** [comment]
> 格式化一下代码文件。

Done，不太明确是否操作正确，感觉可以添加一下相关的说明 。；）

**Comment by panjf2000** [comment]
> > 格式化一下代码文件。
> 
> Done，不太确定是否操作正确，感觉可以添加一下相关的说明 。；）

插件会自动检查并显示具体错误在 github action 上的，可以直接看。

**Pull request closed without merging**
